### ISSUE TITLE
i have an error with the example

### ISSUE THREAD

**Issue by tompeled** [dredwardhyde/librdkafka-example#1]
Hello, 
I have an error, trying to compile and this is what i got:

`1>------ Build started: Project: WindowsProject4, Configuration: Debug Win32 ------
1>KafkaProducer.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl RdKafka::err2str(enum RdKafka::ErrorCode)" (__imp_?err2str@RdKafka@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4ErrorCode@1@@Z) referenced in function _main
1>KafkaProducer.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual __thiscall RdKafka::DeliveryReportCb::~DeliveryReportCb(void)" (__imp_??1DeliveryReportCb@RdKafka@@UAE@XZ) referenced in function "public: virtual __thiscall ExampleDeliveryReportCb::~ExampleDeliveryReportCb(void)" (??1ExampleDeliveryReportCb@@UAE@XZ)
1>KafkaProducer.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __thiscall RdKafka::DeliveryReportCb::DeliveryReportCb(void)" (__imp_??0DeliveryReportCb@RdKafka@@QAE@XZ) referenced in function "public: __thiscall ExampleDeliveryReportCb::ExampleDeliveryReportCb(void)" (??0ExampleDeliveryReportCb@@QAE@XZ)
1>KafkaProducer.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static class RdKafka::Conf * __cdecl RdKafka::Conf::create(enum RdKafka::Conf::ConfType)" (__imp_?create@Conf@RdKafka@@SAPAV12@W4ConfType@12@@Z) referenced in function _main
1>KafkaProducer.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static class RdKafka::Topic * __cdecl RdKafka::Topic::create(class RdKafka::Handle *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class RdKafka::Conf *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &)" (__imp_?create@Topic@RdKafka@@SAPAV12@PAVHandle@2@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PAVConf@2@AAV45@@Z) referenced in function _main
1>KafkaProducer.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static class RdKafka::Producer * __cdecl RdKafka::Producer::create(class RdKafka::Conf *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &)" (__imp_?create@Producer@RdKafka@@SAPAV12@PAVConf@2@AAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) referenced in function _main
1>KafkaProducer.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: static int const RdKafka::Topic::PARTITION_UA" (__imp_?PARTITION_UA@Topic@RdKafka@@2HB)
1>MSVCRTD.lib(exe_winmain.obj) : error LNK2019: unresolved external symbol _WinMain@16 referenced in function "int __cdecl invoke_main(void)" (?invoke_main@@YAHXZ)
1>C:\Users\inbal\source\repos\WindowsProject4\Debug\WindowsProject4.exe : fatal error LNK1120: 8 unresolved externals
1>Done building project "WindowsProject4.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
`

i installed the librdkafka with NUGET and i can't using CMAKE together in visual studio

can you help me please?

**Comment by dredwardhyde** [comment]
Hi, I see some linking errors here, have you added librdkafka headers to input path and library to dependencies? Keep in mind library must be set according to project type (x64 or x86).

**Comment by dredwardhyde** [comment]
Also last linking error:
**error LNK2019: unresolved external symbol _WinMain@16 referenced in function "int __cdecl invoke_main(void)"**
could be resolved by changing project type:
**Properties -> Linker -> System -> SubSystem (in Visual Studio).
from Windows (/SUBSYSTEM:WINDOWS) to Console (/SUBSYSTEM:CONSOLE)**

**Comment by tompeled** [comment]
> Also last linking error:
> **error LNK2019: unresolved external symbol _WinMain@16 referenced in function "int __cdecl invoke_main(void)"**
> could be resolved by changing project type:
> **Properties -> Linker -> System -> SubSystem (in Visual Studio). from Windows (/SUBSYSTEM:WINDOWS) to Console (/SUBSYSTEM:CONSOLE)**

Thank you for your quick reply!  
I did it, but its still not working 
I still have a lot of errors

regarding this question
have you added librdkafka headers to input path and library to dependencies

how i'm add a headers?
in the code i see

#include "librdkafka/rdkafkacpp.h"

is not enough?

**Comment by dredwardhyde** [comment]
Nope. You have downloaded headers (.h) and libraries (.lib) and runtime DLLs (.dll) by nuget, that's fine. 
Now you need to make your project know about those files.
Here's how to do it:
https://docs.microsoft.com/en-us/cpp/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp?view=vs-2019
Steps **To add the DLL header to your include path** and **To add the DLL import library to your project**.
**Also** even after successful build you need to copy .dll files from x86 or x64 librdkafka folder to Debug folder near .exe file (probably WindowsProject4.exe?).

**Comment by tompeled** [comment]
Wow
thank you!
it's works!

**Comment by dredwardhyde** [comment]
Glad to help you! Have a nice day!

**Comment by tompeled** [comment]
Hello, now i have another problem
the consumer  does not work
I run the consumer and It immediately closes it 
Can you have any idea what the problem is?
The Producer works, I see in Kafka and Zookeeper that he connected well

maybe Something that i have to know when i run the consumer?

by the way
I did a test with what's in Kafka, and it works (consumer and producer)
kafka-console-producer.bat --broker-list localhost:9092 --topic test
kafka-console-consumer.bat --zookeeper localhost:2181 --topic test


Thanks!

**Comment by dredwardhyde** [comment]
Do you see any messages in consumer console output?

**Comment by tompeled** [comment]
nop

**Comment by tompeled** [comment]
maybe i see something

Exception thrown at 0x7A901E89 (librdkafkacpp.dll) in Consumer.exe: 0xC0000005: Access violation writing location 0x7A90BA9D.

**Comment by dredwardhyde** [comment]
Well, in main method of consumer .cpp file, you can see few settings that must be set according to your environment. Check it and correct if necessary. Other than that, I don’t have any ideas, you’ve provided too little information.

**Comment by tompeled** [comment]
> maybe i see something
> 
> Exception thrown at 0x7A901E89 (librdkafkacpp.dll) in Consumer.exe: 0xC0000005: Access violation writing location 0x7A90BA9D.

thank you very much for the quick answer!
Doesn't it help you to think about something that could be?

**Comment by dredwardhyde** [comment]
Well, that exception is classic segfault, it means app tried to write something at the memory address 0x7A90BA9D and failed. So, assuming that you’ve placed .dll files near compiled .exe and producer.exe is working just fine - wrong configuration could be the only reason.

**Comment by tompeled** [comment]
Really appreciate your help! 👍 

Maybe I'm asking too much : X
I am attaching the solution project, can you see his settings that everything was set up correctly?

[](http://changes.co.il/Consumer.rar)

For the MAIN,: 
I made sure about the IP, port and message sent
again thank you very much for all!!!

**Comment by tompeled** [comment]
http://changes.co.il/Consumer.rar

**Comment by dredwardhyde** [comment]
Why you haven't change those settings?
```
std::string brokers = "localhost:9091,localhost:9092,localhost:9093";
std::string topic = "telemetry-replicated";

...

conf->set("offset.store.path", "/home/tony/Kafka/offsets", errstr);
	tconf->set("topic.offset.store.path", "/home/tony/Kafka/offsets", errstr);
```

**Comment by tompeled** [comment]
You're right!
I changed it, but it still doesn't work
It just close the window right away that I run it

**Comment by tompeled** [comment]
any other ideas?

**Comment by dredwardhyde** [comment]
No, since you haven't provided any additional information.
I can not teach you how to debug your code.
